"""
Logging filter that scrubs raw genotype data from log messages.

Three classes of leak this is designed to catch:

  1. **Raw rsID genotype lines** in AncestryDNA / 23andMe format —
     `rs12345\\t1\\t767772\\tA\\tG`. Should never appear in logs even if
     a developer accidentally includes one in an exception message.

  2. **AncestryDNA / 23andMe file headers** that explicitly identify the
     file as personal genetic data.

  3. **Long sequences of allele characters** that look like a stretch of
     genotype calls, e.g. dumping a numpy array of dosages or alleles.

Attach the filter to any logger that may touch user data:

    import logging
    from scripts.utils.log_redact import RedactGenotypesFilter
    handler.addFilter(RedactGenotypesFilter())

The filter MUTATES the LogRecord's `msg` and `args` so the redaction
applies regardless of which Formatter is used downstream.
"""
from __future__ import annotations

import logging
import re

# rsid \t chrom \t pos \t a1 \t a2  (TAB or whitespace separated)
RSID_LINE_RE = re.compile(
    r"\brs\d+\s+[0-9MTXYmtxy]+\s+\d+\s+[ACGTacgt0-]\s+[ACGTacgt0-]\b"
)

# Common AncestryDNA / 23andMe header lines (allow-raw-dna: the patterns we
# scrub for must literally appear here as regex source)
DNA_HEADER_RE = re.compile(
    r"AncestryDNA raw data"           # allow-raw-dna
    r"|This data file generated by 23andMe"
    r"|^# rsid\b",
    re.MULTILINE,
)

# Run of allele/dosage chars long enough to be a leak (e.g. "AAGCTGAAA…",
# "012021201210…"). 40-char minimum so we don't false-positive on
# protein-sequence comments or hex strings.
ALLELE_RUN_RE = re.compile(r"[ACGT]{40,}|[012\-]{40,}")

REDACTED = "[REDACTED:dna]"


def _scrub(text: object) -> object:
    """Return a redacted copy of text if it's a string; otherwise unchanged."""
    if not isinstance(text, str):
        return text
    out = DNA_HEADER_RE.sub(REDACTED, text)
    out = RSID_LINE_RE.sub(REDACTED, out)
    out = ALLELE_RUN_RE.sub(REDACTED, out)
    return out


class RedactGenotypesFilter(logging.Filter):
    """
    Strips raw genotype patterns from every LogRecord before it reaches
    a handler. Returns True (record always proceeds — never silently
    dropped) but with sensitive content replaced by `REDACTED`.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        if record.msg is not None:
            record.msg = _scrub(record.msg)
        if record.args:
            if isinstance(record.args, dict):
                record.args = {k: _scrub(v) for k, v in record.args.items()}
            else:
                record.args = tuple(_scrub(a) for a in record.args)
        return True
