"""
Tests for scripts.utils.log_redact — the genotype-scrubbing log filter.

These are critical-path security tests: if redaction silently breaks, raw
genotype lines could leak into Worker logs / Sentry / wherever logs land.
"""
from __future__ import annotations

import logging
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from utils.log_redact import (  # noqa: E402
    RedactGenotypesFilter,
    REDACTED,
    _scrub,
)


# ---------------------------------------------------------------------------
# Direct _scrub() tests
# ---------------------------------------------------------------------------

def test_scrub_rsid_line():
    leaked = "user gt: rs12345\t1\t767772\tA\tG"
    out = _scrub(leaked)
    assert REDACTED in out
    assert "rs12345" not in out
    assert "A\tG" not in out


def test_scrub_ancestrydna_header():
    leaked = "exception when parsing: '# AncestryDNA raw data download'"  # allow-raw-dna
    out = _scrub(leaked)
    assert REDACTED in out
    assert "AncestryDNA raw data" not in out  # allow-raw-dna


def test_scrub_23andme_header():
    leaked = "# This data file generated by 23andMe at: 2024-01-01"
    out = _scrub(leaked)
    assert REDACTED in out
    assert "23andMe" not in out


def test_scrub_long_allele_run():
    leaked = "dosages=" + "A" * 60
    out = _scrub(leaked)
    assert REDACTED in out
    assert "A" * 60 not in out


def test_scrub_dosage_run():
    leaked = "encoded=" + "012021201210" * 5  # 60 chars
    out = _scrub(leaked)
    assert REDACTED in out


def test_scrub_short_allele_run_ok():
    # A short ACGT run (e.g. a 4-char primer sequence) should NOT be scrubbed.
    safe = "primer: ACGT"
    assert _scrub(safe) == safe


def test_scrub_non_string_passthrough():
    assert _scrub(42) == 42
    assert _scrub(None) is None
    assert _scrub([1, 2]) == [1, 2]


def test_scrub_multiple_leaks_in_one_string():
    leaked = (
        "Parse error on row rs12345\t1\t767772\tA\tG "
        "in '# AncestryDNA raw data download'"  # allow-raw-dna
    )
    out = _scrub(leaked)
    assert "rs12345" not in out
    assert "AncestryDNA raw data" not in out  # allow-raw-dna
    assert out.count(REDACTED) >= 2


# ---------------------------------------------------------------------------
# RedactGenotypesFilter integration tests
# ---------------------------------------------------------------------------

class _CapturingHandler(logging.Handler):
    def __init__(self):
        super().__init__()
        self.records: list[logging.LogRecord] = []

    def emit(self, record: logging.LogRecord) -> None:
        # Force argument interpolation now so the assertions see the final text.
        record.message = record.getMessage()
        self.records.append(record)


def _make_logger() -> tuple[logging.Logger, _CapturingHandler]:
    logger = logging.getLogger(f"test.{id(object())}")
    logger.handlers.clear()
    logger.setLevel(logging.DEBUG)
    handler = _CapturingHandler()
    handler.addFilter(RedactGenotypesFilter())
    logger.addHandler(handler)
    return logger, handler


def test_filter_redacts_rsid_in_log_message():
    logger, h = _make_logger()
    logger.info("failed at rs12345\t1\t767772\tA\tG please debug")
    assert len(h.records) == 1
    assert "rs12345" not in h.records[0].getMessage()
    assert REDACTED in h.records[0].getMessage()


def test_filter_redacts_in_format_args():
    logger, h = _make_logger()
    leaked = "rs98765\tY\t12345\tC\tT"
    logger.warning("user line: %s", leaked)
    msg = h.records[0].getMessage()
    assert "rs98765" not in msg
    assert REDACTED in msg


def test_filter_allows_clean_messages_through():
    logger, h = _make_logger()
    logger.info("Pipeline started for user %s", "user-abc")
    msg = h.records[0].getMessage()
    assert msg == "Pipeline started for user user-abc"
    assert REDACTED not in msg


def test_filter_handles_exception_string():
    logger, h = _make_logger()
    try:
        raise ValueError("Bad row: rs12345\t1\t767772\tA\tG")
    except ValueError as e:
        logger.exception("Caught: %s", str(e))
    msg = h.records[0].getMessage()
    assert "rs12345" not in msg
    assert REDACTED in msg
