#!/usr/bin/env python3
"""
Step 1.6 — Interpretation and Report Synthesis.

Consolidates outputs from steps 1.1, 1.2, 1.3, 1.4, and 1.5 into:

  - report.json       — single structured document for the future web UI
  - map_data.geojson  — FeatureCollection of ancient match locations
                        (top autosomal + top Y-haplogroup matches), each
                        with the data needed to render an interactive map

The Markdown narrative is still generated by run_local.py's build_report;
this step produces the *machine-consumable* artefacts. The JSON schema
here is the template the Phase 2 web platform will consume from D1/R2.

Inputs:
  output/step1_<label>/step1_summary.json
  output/step2_<label>/{ydna,mtdna}_haplogroup.json
  output/step2_<label>/ancient_haplogroup_matches.tsv
  output/step3_<label>/pairwise_distances.tsv
  output/step3_<label>/population_distances.tsv
  output/step3_<label>/pca_coordinates.tsv
  output/step3_<label>/pca_variance_explained.json
  output/step1_4_<label>/tmrca_timeline.json
  output/step1_5_<label>/admixture_decomposition.json

Outputs (output/step1_6_<label>/):
  report.json
  map_data.geojson

Usage:
  python scripts/step1_6_synthesis.py
"""

from __future__ import annotations

import json
import logging
import os
import sys
import time
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
OUTPUT_LABEL = os.environ.get("OUTPUT_LABEL", "rn")
N_TOP_INDIVIDUAL_MATCHES = 30
N_TOP_POPULATION_MATCHES = 20
N_TOP_HAPLOGROUP_MATCHES = 20
MIN_INDIV_SNPS_FOR_MAP   = 50_000  # exclude low-coverage individuals from map

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent.parent
OUT1   = ROOT / "output" / f"step1_{OUTPUT_LABEL}"
OUT2   = ROOT / "output" / f"step2_{OUTPUT_LABEL}"
OUT3   = ROOT / "output" / f"step3_{OUTPUT_LABEL}"
OUT1_4 = ROOT / "output" / f"step1_4_{OUTPUT_LABEL}"
OUT1_5 = ROOT / "output" / f"step1_5_{OUTPUT_LABEL}"
OUTPUT = ROOT / "output" / f"step1_6_{OUTPUT_LABEL}"
OUTPUT.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(message)s",
    datefmt="%H:%M:%S",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(OUTPUT / "step1_6.log", mode="w"),
    ],
)
log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def read_json(path: Path) -> dict | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except Exception as e:
        log.warning("Could not parse %s: %s", path, e)
        return None


def read_tsv_rows(path: Path, limit: int | None = None) -> list[dict]:
    """Read a TSV into a list of dicts. Limit applies after parsing."""
    if not path.exists():
        return []
    rows: list[dict] = []
    with open(path) as fh:
        header = fh.readline().rstrip("\n").split("\t")
        for line in fh:
            if limit is not None and len(rows) >= limit:
                break
            rows.append(dict(zip(header, line.rstrip("\n").split("\t"))))
    return rows


def to_float(s: str) -> float | None:
    if s in ("", "NA", "n/a", "n/a (female)"):
        return None
    try:
        return float(s)
    except ValueError:
        return None


def to_int(s: str) -> int | None:
    f = to_float(s)
    return int(f) if f is not None else None


# ---------------------------------------------------------------------------
# Build structured report
# ---------------------------------------------------------------------------

def build_report() -> dict[str, Any]:
    step1   = read_json(OUT1   / "step1_summary.json")             or {}
    ydna    = read_json(OUT2   / "ydna_haplogroup.json")           or {}
    mtdna   = read_json(OUT2   / "mtdna_haplogroup.json")          or {}
    pca_var = read_json(OUT3   / "pca_variance_explained.json")    or {}
    tmrca   = read_json(OUT1_4 / "tmrca_timeline.json")            or {}
    admix   = read_json(OUT1_5 / "admixture_decomposition.json")   or {}

    # Top individual matches (autosomal ASD ranking), coverage-filtered
    indiv_rows = read_tsv_rows(OUT3 / "pairwise_distances.tsv")
    indiv_matches: list[dict] = []
    for r in indiv_rows:
        n_snps = to_int(r.get("snps_compared", ""))
        asd    = to_float(r.get("asd_distance", ""))
        if n_snps is None or asd is None:
            continue
        if n_snps < MIN_INDIV_SNPS_FOR_MAP:
            continue
        indiv_matches.append({
            "genetic_id":       r["genetic_id"],
            "population":       r["group_id"],
            "locality":         r["locality"],
            "political_entity": r["political_entity"],
            "lat":              to_float(r["lat"]),
            "lon":              to_float(r["lon"]),
            "date_bp":          to_float(r["date_bp"]),
            "date_display":     r["date_display"],
            "y_haplogroup":     r["y_haplogroup"],
            "mt_haplogroup":    r["mt_haplogroup"],
            "snps_compared":    n_snps,
            "asd":              asd,
        })
    indiv_matches.sort(key=lambda x: x["asd"])
    indiv_top = indiv_matches[:N_TOP_INDIVIDUAL_MATCHES]
    for rank, m in enumerate(indiv_top, start=1):
        m["rank"] = rank

    # Top population matches
    pop_rows = read_tsv_rows(OUT3 / "population_distances.tsv")
    pop_top: list[dict] = []
    for r in pop_rows[:N_TOP_POPULATION_MATCHES]:
        pop_top.append({
            "rank":             to_int(r["rank"]),
            "population":       r["population"],
            "n_individuals":    to_int(r["n_individuals"]),
            "mean_distance":    to_float(r["mean_distance"]),
            "min_distance":     to_float(r["min_distance"]),
            "median_distance":  to_float(r["median_distance"]),
            "date_display":     r.get("date_display", ""),
            "locality":         r.get("locality", ""),
            "political_entity": r.get("political_entity", ""),
            "lat":              to_float(r.get("lat", "")),
            "lon":              to_float(r.get("lon", "")),
        })

    # Top haplogroup matches from step 2
    hg_rows = read_tsv_rows(OUT2 / "ancient_haplogroup_matches.tsv",
                            limit=N_TOP_HAPLOGROUP_MATCHES)
    hg_top: list[dict] = []
    for r in hg_rows:
        hg_top.append({
            "genetic_id":            r["genetic_id"],
            "population":            r["group_id"],
            "locality":              r["locality"],
            "political_entity":      r["political_entity"],
            "lat":                   to_float(r["lat"]),
            "lon":                   to_float(r["lon"]),
            "date_bp":               to_float(r["date_bp"]),
            "date_display":          r["date_display"],
            "molecular_sex":         r["molecular_sex"],
            "ancient_y_haplogroup":  r["ancient_y_haplogroup"],
            "ancient_mt_haplogroup": r["ancient_mt_haplogroup"],
            "match_type":            r["match_type"],
            "combined_score":        to_int(r["combined_score"]),
            "assessment":            r["assessment"],
        })

    # PCA — modern coords + a sample of ancients (for plotting context)
    pca_rows = read_tsv_rows(OUT3 / "pca_coordinates.tsv")
    modern_pca = None
    for r in pca_rows:
        if r.get("type") == "modern":
            modern_pca = {
                f"PC{i}": to_float(r.get(f"PC{i}", "")) for i in range(1, 11)
            }
            break

    # Anomalies / quality flags
    anomalies: list[str] = []
    if ydna.get("confidence") == "low":
        anomalies.append(
            f"Y-DNA haplogroup confidence is LOW "
            f"({ydna.get('markers_checked', 0)} markers checked, "
            f"{ydna.get('markers_not_on_array', 0)} not on array)"
        )
    if mtdna.get("confidence") == "low":
        anomalies.append(
            f"mtDNA haplogroup confidence is LOW "
            f"({mtdna.get('positions_checked', 0)} positions checked)"
        )
    overlap_n = (step1.get("overlap") or {}).get("n_overlap_snps")
    if overlap_n is not None and overlap_n < 100_000:
        anomalies.append(
            f"SNP overlap with AADR is small ({overlap_n:,} SNPs) — "
            f"results may be unreliable"
        )
    if tmrca.get("skipped"):
        anomalies.append(f"Step 1.4 TMRCA skipped: {tmrca.get('reason', 'unknown reason')}")

    return {
        "label":         OUTPUT_LABEL,
        "generated_at":  time.strftime("%Y-%m-%dT%H:%M:%S"),
        "schema_version": "1.0",
        "modern_individual": {
            "snps_called":   (step1.get("modern_individual") or {}).get("total_snps"),
            "y_haplogroup":  {
                "value":      ydna.get("haplogroup"),
                "confidence": ydna.get("confidence"),
                "notes":      ydna.get("notes"),
            },
            "mt_haplogroup": {
                "value":      mtdna.get("haplogroup"),
                "confidence": mtdna.get("confidence"),
            },
        },
        "ancient_dataset": {
            "individuals":   (step1.get("ancient_dataset") or {}).get("n_individuals"),
            "snps":          (step1.get("ancient_dataset") or {}).get("n_snps_geno_header"),
            "snp_overlap":   overlap_n,
        },
        "admixture":         admix,
        "y_tmrca":           tmrca,
        "haplogroup_matches": hg_top,
        "top_population_matches": pop_top,
        "top_individual_matches": indiv_top,
        "pca": {
            "modern_coords":       modern_pca,
            "variance_explained":  pca_var.get("eigenvalues"),
            "n_components":        len(pca_var.get("eigenvalues") or []),
        },
        "anomalies": anomalies,
    }


# ---------------------------------------------------------------------------
# Build GeoJSON
# ---------------------------------------------------------------------------

def build_geojson(report: dict[str, Any]) -> dict[str, Any]:
    """
    FeatureCollection of points for the map. Each ancient match becomes a
    feature with properties describing its date, population, match type,
    and the relevant similarity metric (ASD for autosomal matches; TMRCA
    for Y-haplogroup matches).
    """
    features: list[dict] = []

    # Autosomal individual matches (top N by ASD)
    for m in report["top_individual_matches"]:
        if m["lat"] is None or m["lon"] is None:
            continue
        features.append({
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [m["lon"], m["lat"]]},
            "properties": {
                "match_type":     "autosomal",
                "rank":           m["rank"],
                "genetic_id":     m["genetic_id"],
                "population":     m["population"],
                "locality":       m["locality"],
                "country":        m["political_entity"],
                "date_bp":        m["date_bp"],
                "date_display":   m["date_display"],
                "y_haplogroup":   m["y_haplogroup"],
                "mt_haplogroup":  m["mt_haplogroup"],
                "asd_distance":   m["asd"],
                "snps_compared":  m["snps_compared"],
            },
        })

    # Y-TMRCA matches (from step 1.4)
    if not report["y_tmrca"].get("skipped"):
        for m in report["y_tmrca"].get("matches", []):
            if m.get("lat") is None or m.get("lon") is None:
                continue
            features.append({
                "type": "Feature",
                "geometry": {"type": "Point", "coordinates": [m["lon"], m["lat"]]},
                "properties": {
                    "match_type":      "y_tmrca",
                    "genetic_id":      m["genetic_id"],
                    "population":      m["population"],
                    "locality":        m.get("locality"),
                    "date_bp":         m.get("date_bp"),
                    "date_display":    m.get("date_display"),
                    "ancient_y_haplogroup": m.get("ancient_y_haplogroup"),
                    "n_y_sites":       m.get("n_y_sites"),
                    "n_diff":          m.get("n_diff"),
                    "diff_rate":       m.get("diff_rate"),
                    "tmrca_yr":        m.get("tmrca_yr"),
                    "tmrca_lo_95":     m.get("tmrca_lo_95"),
                    "tmrca_hi_95":     m.get("tmrca_hi_95"),
                },
            })

    return {
        "type": "FeatureCollection",
        "metadata": {
            "label":        report["label"],
            "generated_at": report["generated_at"],
            "n_features":   len(features),
            "match_types": ["autosomal", "y_tmrca"],
            "notes": (
                "Each Point is one ancient sample. 'match_type=autosomal' = top "
                "genome-wide ASD matches from step 1.3. 'match_type=y_tmrca' = top "
                "Y-haplogroup matches from step 2 with TMRCA estimates from step 1.4."
            ),
        },
        "features": features,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    log.info("=== Step 1.6 — Synthesis ===")
    log.info("Label: %s", OUTPUT_LABEL)

    t0 = time.time()
    report = build_report()
    geojson = build_geojson(report)

    report_path  = OUTPUT / "report.json"
    geojson_path = OUTPUT / "map_data.geojson"

    report_path.write_text(json.dumps(report, indent=2, default=str))
    geojson_path.write_text(json.dumps(geojson, indent=2, default=str))

    log.info("Wrote %s  (%d top individual matches, %d top populations, %d haplogroup matches)",
             report_path,
             len(report["top_individual_matches"]),
             len(report["top_population_matches"]),
             len(report["haplogroup_matches"]))
    log.info("Wrote %s  (%d features)", geojson_path, len(geojson["features"]))
    if report["anomalies"]:
        log.warning("Anomalies flagged:")
        for a in report["anomalies"]:
            log.warning("  - %s", a)
    log.info("=== Step 1.6 complete in %.1fs ===", time.time() - t0)


if __name__ == "__main__":
    main()
